name: hwtome
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - cudatoolkit
  - pytorch>=2.1.0
  - torchvision
  - numpy
  - timm>=0.9.0
  - jupyter
  - dinov2
  - pip:
    - pillow
    - tqdm
    - scipy
